### ISSUE TITLE
请求添加自定义字体功能

### ISSUE THREAD

**Issue by Jiabinone** [kangfenmao/cherry-studio#200]
由于习惯了编程字体,字体大小不一致,看起来有些不适应.希望添加这个功能.

**Comment by Jiabinone** [comment]
备注:我使用系统 macos

**Comment by kangfenmao** [comment]
收到，需求逻辑已经清晰，合并到这里：https://github.com/kangfenmao/cherry-studio/issues/158

**Comment by Jiabinone** [comment]
老哥,好几个月过去了,自定义字体的功能还没有啊.眼都花了

**Comment by kangfenmao** [comment]
设置 -> 显示设置 -> 自定义 CSS

```css
/* 使用通配符选择器应用于所有元素 */
* {
    font-family: "PingFang SC", -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif !important;
}

/* 或者为特定元素设置 */
h1, h2, h3, h4, h5, h6, p, li, a {
    font-family: "PingFang SC", -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif !important;
}
```
