### ISSUE TITLE
代码块里的内容没有自动换行

### ISSUE THREAD

**Issue by crybest** [kangfenmao/cherry-studio#353]
![image](https://github.com/user-attachments/assets/5a0268ce-0c74-417c-abbf-154c10a63cca)
如图所示

**Comment by ZzzzRyan** [comment]
大部分代码块本身就是**不支持自动换行**的。因为对于代码来说，逻辑和语法一般都是按行分割的，自动换行反而会造成代码阅读的混乱。

如果要兼容这种把文字放在代码块里的非常规做法，或许得添加自动换行的选项开关。

**Comment by kangfenmao** [comment]
这个应该不会支持了，代码不换行是特意加上的

**Comment by Chnja** [comment]
可以自己在CSS里面添加
```css
pre > code {
  white-space: pre-wrap;       /* 保留空格，自动换行 */
  word-wrap: break-word;       /* 允许长单词断行 */
}
```
